import Head from "next/head";
import Link from "next/link";
import { motion, AnimatePresence } from "framer-motion";
import useBackground from "../context/BackgroundContext";
import homeStyles from "../styles/Home.module.scss";

export default function Home() {
  const { setBackground } = useBackground();

  const videoAnim = {
    hidden: {
      opacity: 0,
      scale: 1.1,
      transition: {
        duration: 1,
        delay: 1,
        ease: "easeInOut",
      },
    },
    visible: {
      opacity: 1,
      scale: 1,
      transition: {
        duration: 0.5,
        ease: "easeInOut",
      },
    },
  };

  const heightAnim = {
    hidden: {
      height: "0%",
      transition: {
        duration: 0.5,
        delay: 0.2,
        ease: "easeInOut",
        when: "afterChildren",
      },
    },
    visible: {
      height: "100%",
      transition: {
        duration: 0.5,
        ease: "easeInOut",
        when: "beforeChildren",
      },
    },
  };

  const opacityAnim = {
    hidden: {
      opacity: 0,
    },
    visible: {
      opacity: 1,
    },
  };

  return (
    <div className={homeStyles.container}>
      <Head>
        <title>George</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={homeStyles.main}>
        {/* VIDEO */}
        <div className={homeStyles.outer}>
          <motion.div
            variants={videoAnim}
            initial="hidden"
            animate="visible"
            exit="hidden"
            dangerouslySetInnerHTML={{
              __html: `<video autoplay loop muted playsinline>
                        <source src="/video.mp4" type="video/mp4" />
                        </video>`,
            }}
          />
        </div>

        {/* CONTENT */}
        <div className={homeStyles.content}>
          <div className={homeStyles.col}></div>
          {/* CENTER */}

          <motion.div
            className={`${homeStyles.col} ${homeStyles.center}`}
            variants={heightAnim}
            initial="hidden"
            animate="visible"
            exit="hidden">
            {/* LINE_1 */}
            <div className={homeStyles.line1}>
              <AnimatePresence>
                <Link href="/showcase">
                  <motion.a variants={opacityAnim} className={homeStyles.link1}>
                    <div
                      className={homeStyles.linkContainer}
                      onMouseEnter={() => setBackground(false)}
                      onMouseLeave={() => setBackground(true)}>
                      <span className={homeStyles.small}>MY PROJECTS</span>
                      <span className={homeStyles.large}>EXPLORE NOW</span>
                    </div>
                  </motion.a>
                </Link>
              </AnimatePresence>
            </div>

            {/* LINE_2 */}
            <div className={homeStyles.line2}>
              <AnimatePresence>
                <Link href="/contact">
                  <motion.a variants={opacityAnim}>
                    <div
                      className={homeStyles.linkContainer2}
                      onMouseEnter={() => setBackground(false)}
                      onMouseLeave={() => setBackground(true)}>
                      <span className={homeStyles.large}>HOW TO FIND ME</span>
                      <span className={homeStyles.small}>CONTACT ME</span>
                    </div>
                  </motion.a>
                </Link>
              </AnimatePresence>
            </div>
          </motion.div>

          {/* ------ */}
          <div className={homeStyles.col}></div>
        </div>
      </main>
    </div>
  );
}
